package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
)

// CognitoConfig represents the Cognito configuration from Terraform
type CognitoConfig struct {
	UserPoolID string `json:"userPoolId"`
	ClientID   string `json:"clientId"`
	Endpoint   string `json:"endpoint"`
	Region     string `json:"region"`
}

// AuthResult holds the JWT tokens returned from Cognito
type AuthResult struct {
	IDToken      string `json:"id_token"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int32  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

// JWTAuthClient demonstrates JWT authentication with Terraform-provisioned Cognito
type JWTAuthClient struct {
	client        *cognitoidentityprovider.Client
	cognitoConfig *CognitoConfig
}

// NewJWTAuthClient creates a new JWT authentication client
func NewJWTAuthClient(configPath string) (*JWTAuthClient, error) {
	// Load Cognito configuration (generated by Terraform setup)
	cognitoConfig, err := loadCognitoConfig(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to load config: %w", err)
	}

	ctx := context.Background()

	// Create AWS SDK client
	client, err := createCognitoClient(ctx, cognitoConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to create Cognito client: %w", err)
	}

	return &JWTAuthClient{
		client:        client,
		cognitoConfig: cognitoConfig,
	}, nil
}

// Login authenticates a user and returns JWT tokens
func (j *JWTAuthClient) Login(ctx context.Context, username, password string) (*AuthResult, error) {
	fmt.Println("🔐 Authenticating user with Cognito...")

	result, err := j.client.InitiateAuth(ctx, &cognitoidentityprovider.InitiateAuthInput{
		AuthFlow: types.AuthFlowTypeUserPasswordAuth,
		ClientId: aws.String(j.cognitoConfig.ClientID),
		AuthParameters: map[string]string{
			"USERNAME": username,
			"PASSWORD": password,
		},
	})

	if err != nil {
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	if result.AuthenticationResult == nil {
		return nil, fmt.Errorf("authentication result is nil")
	}

	auth := result.AuthenticationResult
	return &AuthResult{
		IDToken:      *auth.IdToken,
		AccessToken:  *auth.AccessToken,
		RefreshToken: *auth.RefreshToken,
		ExpiresIn:    auth.ExpiresIn,
		TokenType:    *auth.TokenType,
	}, nil
}

// RefreshTokens gets new JWT tokens using a refresh token
func (j *JWTAuthClient) RefreshTokens(ctx context.Context, refreshToken string) (*AuthResult, error) {
	fmt.Println("🔄 Refreshing JWT tokens...")

	result, err := j.client.InitiateAuth(ctx, &cognitoidentityprovider.InitiateAuthInput{
		AuthFlow: types.AuthFlowTypeRefreshTokenAuth,
		ClientId: aws.String(j.cognitoConfig.ClientID),
		AuthParameters: map[string]string{
			"REFRESH_TOKEN": refreshToken,
		},
	})

	if err != nil {
		return nil, fmt.Errorf("token refresh failed: %w", err)
	}

	auth := result.AuthenticationResult
	return &AuthResult{
		IDToken:     *auth.IdToken,
		AccessToken: *auth.AccessToken,
		ExpiresIn:   auth.ExpiresIn,
		TokenType:   *auth.TokenType,
	}, nil
}

// GetUserInfo retrieves user information using an access token
func (j *JWTAuthClient) GetUserInfo(ctx context.Context, accessToken string) (map[string]string, error) {
	fmt.Println("👤 Retrieving user info...")

	result, err := j.client.GetUser(ctx, &cognitoidentityprovider.GetUserInput{
		AccessToken: aws.String(accessToken),
	})

	if err != nil {
		return nil, fmt.Errorf("failed to get user info: %w", err)
	}

	userInfo := map[string]string{
		"username": *result.Username,
	}

	for _, attr := range result.UserAttributes {
		userInfo[*attr.Name] = *attr.Value
	}

	return userInfo, nil
}

// Helper functions

func loadCognitoConfig(path string) (*CognitoConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var cfg CognitoConfig
	err = json.Unmarshal(data, &cfg)
	return &cfg, err
}

func createCognitoClient(ctx context.Context, cognitoConfig *CognitoConfig) (*cognitoidentityprovider.Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(cognitoConfig.Region),
		config.WithEndpointResolverWithOptions(
			aws.EndpointResolverWithOptionsFunc(
				func(service, region string, options ...interface{}) (aws.Endpoint, error) {
					if service == cognitoidentityprovider.ServiceID {
						return aws.Endpoint{
							URL:           cognitoConfig.Endpoint,
							SigningRegion: cognitoConfig.Region,
						}, nil
					}
					return aws.Endpoint{}, fmt.Errorf("unknown endpoint requested")
				},
			),
		),
	)
	if err != nil {
		return nil, err
	}

	return cognitoidentityprovider.NewFromConfig(cfg), nil
}

func saveTokens(authResult *AuthResult, filename string) error {
	data, err := json.MarshalIndent(authResult, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filename, data, 0600)
}

func printTokenInfo(authResult *AuthResult) {
	fmt.Println("\n✅ Authentication Successful!")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Printf("Token Type: %s\n", authResult.TokenType)
	fmt.Printf("Expires In: %d seconds (%d minutes)\n", authResult.ExpiresIn, authResult.ExpiresIn/60)

	fmt.Println("\n📝 JWT Tokens:")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

	// Safely display token previews with length checks
	if len(authResult.IDToken) > 80 {
		fmt.Printf("\n🔑 ID Token (first 80 chars):\n%s...\n", authResult.IDToken[:80])
	} else {
		fmt.Printf("\n🔑 ID Token:\n%s\n", authResult.IDToken)
	}
	
	if len(authResult.AccessToken) > 80 {
		fmt.Printf("\n🎫 Access Token (first 80 chars):\n%s...\n", authResult.AccessToken[:80])
	} else {
		fmt.Printf("\n🎫 Access Token:\n%s\n", authResult.AccessToken)
	}
	
	if len(authResult.RefreshToken) > 80 {
		fmt.Printf("\n🔄 Refresh Token (first 80 chars):\n%s...\n", authResult.RefreshToken[:80])
	} else {
		fmt.Printf("\n🔄 Refresh Token:\n%s\n", authResult.RefreshToken)
	}

	fmt.Println("\n💡 What these tokens do:")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("• ID Token: Contains user identity and attributes (email, name, groups)")
	fmt.Println("• Access Token: Used to access protected API endpoints")
	fmt.Println("• Refresh Token: Used to get new ID and Access tokens when they expire")
}

func printUserInfo(userInfo map[string]string) {
	fmt.Println("\n👤 User Information:")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Printf("Username: %s\n", userInfo["username"])
	fmt.Printf("Email: %s\n", userInfo["email"])
	if name, ok := userInfo["name"]; ok {
		fmt.Printf("Name: %s\n", name)
	}
	if sub, ok := userInfo["sub"]; ok {
		fmt.Printf("User ID (sub): %s\n", sub)
	}
}

// Example usage
func main() {
	fmt.Println("🚀 JWT Authentication Example with Terraform Cognito")
	fmt.Println("====================================================")

	// Configuration
	configPath := "infra-localstack/cognito-local-config/config.json"
	username := "user@example.com"
	password := "PassTemp123!"

	// Check if config exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		log.Fatalf(`
❌ Configuration file not found: %s

To set up Cognito locally:
1. make cognito-local-start
2. make cognito-local-setup
3. Run this example again

Or use a different configuration file path.
`, configPath)
	}

	ctx := context.Background()

	// Create JWT auth client
	client, err := NewJWTAuthClient(configPath)
	if err != nil {
		log.Fatalf("Failed to create JWT auth client: %v", err)
	}

	// 1. Login and get JWT tokens
	fmt.Printf("\n1️⃣  Logging in as: %s\n", username)
	authResult, err := client.Login(ctx, username, password)
	if err != nil {
		log.Fatalf("Login failed: %v", err)
	}

	printTokenInfo(authResult)

	// Save tokens to file
	tokensFile := "tokens.json"
	if err := saveTokens(authResult, tokensFile); err != nil {
		log.Printf("Warning: Failed to save tokens: %v", err)
	} else {
		fmt.Printf("\n💾 Tokens saved to: %s\n", tokensFile)
	}

	// 2. Get user info using access token
	fmt.Println("\n2️⃣  Getting user information...")
	userInfo, err := client.GetUserInfo(ctx, authResult.AccessToken)
	if err != nil {
		log.Printf("Failed to get user info: %v", err)
	} else {
		printUserInfo(userInfo)
	}

	// 3. Demonstrate token refresh
	fmt.Println("\n3️⃣  Demonstrating token refresh...")
	fmt.Println("Waiting 5 seconds before refreshing...")
	time.Sleep(5 * time.Second)

	newAuth, err := client.RefreshTokens(ctx, authResult.RefreshToken)
	if err != nil {
		log.Printf("Failed to refresh tokens: %v", err)
	} else {
		fmt.Println("✅ Tokens refreshed successfully!")
		if len(newAuth.IDToken) > 80 {
			fmt.Printf("New ID Token (first 80 chars): %s...\n", newAuth.IDToken[:80])
		} else {
			fmt.Printf("New ID Token: %s\n", newAuth.IDToken)
		}
		if len(newAuth.AccessToken) > 80 {
			fmt.Printf("New Access Token (first 80 chars): %s...\n", newAuth.AccessToken[:80])
		} else {
			fmt.Printf("New Access Token: %s\n", newAuth.AccessToken)
		}
	}

	fmt.Println("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("✨ Example completed successfully!")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("\n📚 Next steps:")
	fmt.Println("• View the tokens in tokens.json")
	fmt.Println("• Decode the JWT at https://jwt.io/")
	fmt.Println("• See JWT-WITH-TERRAFORM.md for validation examples")
	fmt.Println("• Implement middleware to protect your API routes")
}
