name: CI

on:
  push:
    branches: [ main, develop, feat/Sprint0 ]
  pull_request:
    branches: [ main, develop, feat/Sprint0 ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./cmd/api/main.go

  unit-and-e2e-tests:
    name: Unit and E2E Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Go env
        run: |
          go env
          go version

      - name: Tidy
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Run tests (race + coverage)
        run: |
          go test ./... -race -covermode=atomic -coverprofile=coverage.out -v

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [build, unit-and-e2e-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: const-software-25-02:ci
