name: Verificar Contribuições Copilot

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify-copilot-contributions:
    name: Verificar Contribuições do Copilot
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Verificar contribuições do Copilot
      id: verify
      run: |
        echo "## 🤖 Verificação de Contribuições do Copilot" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Verificar se há commits do Copilot neste PR
        COPILOT_COMMITS=$(git log origin/develop..HEAD --author="copilot" --oneline)
        
        if [ -z "$COPILOT_COMMITS" ]; then
          echo "✅ Nenhuma contribuição do Copilot detectada neste PR." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Todas as mudanças foram feitas pela equipe." >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Contribuições do Copilot detectadas:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$COPILOT_COMMITS" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📝 Ação Necessária" >> $GITHUB_STEP_SUMMARY
          echo "Por favor, atualize o arquivo \`COPILOT_INSTRUCTIONS.md\` para documentar essas contribuições." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Listar arquivos modificados pelos commits do Copilot
          echo "### 📂 Arquivos Modificados pelo Copilot" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          git log origin/develop..HEAD --author="copilot" --name-only --pretty=format: | sort -u | grep -v '^$' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "*Esta verificação garante que o COPILOT_INSTRUCTIONS.md reflita com precisão as contribuições do GitHub Copilot.*" >> $GITHUB_STEP_SUMMARY
    
    - name: Verificar se COPILOT_INSTRUCTIONS.md foi atualizado
      if: success()
      run: |
        # Verificar se há commits do Copilot
        COPILOT_COMMITS=$(git log origin/develop..HEAD --author="copilot" --oneline)
        
        if [ ! -z "$COPILOT_COMMITS" ]; then
          # Verificar se COPILOT_INSTRUCTIONS.md foi modificado neste PR
          INSTRUCTIONS_MODIFIED=$(git diff origin/develop..HEAD --name-only | grep "COPILOT_INSTRUCTIONS.md" || true)
          
          if [ -z "$INSTRUCTIONS_MODIFIED" ]; then
            echo "⚠️ AVISO: Contribuições do Copilot detectadas, mas COPILOT_INSTRUCTIONS.md não foi atualizado."
            echo "Por favor, atualize o arquivo COPILOT_INSTRUCTIONS.md para documentar as novas contribuições."
            exit 0  # Não falhar o workflow, apenas avisar
          else
            echo "✅ COPILOT_INSTRUCTIONS.md foi atualizado neste PR."
          fi
        fi
    
    - name: Comentário no PR (se necessário)
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          
          try {
            const copilotCommits = execSync('git log origin/develop..HEAD --author="copilot" --oneline', { encoding: 'utf-8' });
            
            if (copilotCommits.trim()) {
              const instructionsModified = execSync('git diff origin/develop..HEAD --name-only | grep "COPILOT_INSTRUCTIONS.md" || true', { encoding: 'utf-8' });
              
              if (!instructionsModified.trim()) {
                const comment = `## 🤖 Verificação de Contribuições do Copilot\n\n` +
                  `⚠️ Este PR contém contribuições do GitHub Copilot, mas o arquivo \`COPILOT_INSTRUCTIONS.md\` não foi atualizado.\n\n` +
                  `### Commits do Copilot detectados:\n\`\`\`\n${copilotCommits}\`\`\`\n\n` +
                  `**Ação recomendada:** Por favor, atualize o \`COPILOT_INSTRUCTIONS.md\` para documentar essas contribuições com precisão.`;
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: comment
                });
              }
            }
          } catch (error) {
            console.log('Erro ao verificar commits do Copilot:', error.message);
          }
